SET FOREIGN_KEY_CHECKS = 0;
drop view if exists as_train;
drop table if exists demo_set;
drop view if exists drf_train;
drop table if exists entity_in;
drop table if exists entity_out;
drop view if exists hn_train;
drop view if exists hp_train;
drop view if exists ih_train;
drop view if exists mm_train;
drop view if exists modr_train;
drop view if exists modu_train;
drop table if exists relation;
drop table if exists result_cn;
drop table if exists result_jc;
drop table if exists result_pa;
drop table if exists result_rel;
drop view if exists sdto_train;
drop table if exists st_train;
drop table if exists test_set;
drop view if exists vg_train;
drop table if exists wn18rr;
drop table if exists wn18rr_test;
drop table if exists wn18rr_train;
drop table if exists wn18rr_valid;
SET FOREIGN_KEY_CHECKS = 1;